const placeTypeMap = {
  bar: "酒吧",
  pub: "酒館",
  liquor_store: "酒類專賣店",
  restaurant: "餐廳",
  brewery: "精釀啤酒廠",
  cocktail_bar: "調酒",
  izakaya: "居酒屋",
  wine_bar: "葡萄酒吧",
  sports_bar: "運動酒吧",
  jazz_club: "爵士樂酒吧",
  karaoke_bar: "KTV酒吧",
  lounge: "Lounge Bar",
  rooftop_bar: "頂樓酒吧",
  speakeasy: "隱密酒吧",
  night_club: "夜店",
  // 偏向「地點特色」或「服務/氛圍」，可能需要從評論或網站解析，或作為自定義標籤
  live_music: "現場音樂",
  late_night: "深夜營業",
  outdoor_seating: "戶外座位",
  smoking_area: "吸煙區",
  darts: "飛鏢",
  happy_hour: "歡樂時光",
  good_for_groups: "適合團體",
  romantic: "浪漫氛圍",
  casual: "輕鬆休閒",
  elegant: "高雅",
  pool_table: "撞球",
  board_games: "桌遊",
  wifi: "免費Wifi",
  reservations: "可預訂",
  snacks: "提供小點",
  food_service: "提供餐點",
  non_alcoholic: "無酒精飲品",
  craft_beer: "特色啤酒",
  local_beer: "在地啤酒",
};

export default placeTypeMap;
